name        : packagekit
version     : 1.0.10
release     : 8
source     :
    - http://www.freedesktop.org/software/PackageKit/releases/PackageKit-1.0.10.tar.xz : e56b8efac6733763d6f525b6436c75585be2194d67d7c4cdeaed82e6c6c6feac
license     :
    - GPL-2.0
summary     : D-Bus abstraction layer that allows the session user to manage packages in a secure way using a cross-distro, cross-architecture API.
builddeps   :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(sqlite3)
description : |
    PackageKit is a system designed to make installing and updating software on your computer easier. The primary design goal is to unify all the software graphical tools used in different distributions, and use some of the latest technology like PolicyKit to make the process suck less.
setup      : |
    # TEMPORARY: Swapping for new eopkg soon.
    %configure --enable-pisi \
               --with-default-backend=pisi \
               --disable-dummy \
               --disable-bash-completion \
               --disable-man-pages \
               --disable-static \
               --enable-systemd
build      : |
    %make
install    : |
    %make_install
     
    install -m 00644 -D $pkgfiles/pisi.conf $installdir/etc/PackageKit/pisi.conf
