name       : packagekit
version    : 1.2.6
release    : 1
source     :
    - git|https://github.com/joebonrichie/PackageKit.git : ac22b0a13e122d0086579533a927904474dec7b3
license    : GPL-2.0-or-later
component  : programming.library
homepage   : https://www.freedesktop.org/software/PackageKit/
summary    : A D-BUS abstraction layer that allows the user to manage packages in a secure way using a cross-distro, cross-architecture API. (NOT SUPPORTED)
description: |
    This package is experimental and not supported! Help will not currently be provided.
    PackageKit is a DBUS abstraction layer that allows the session user to manage packages in a secure way using a cross-distro, cross-architecture API.
builddeps  :
    - pkgconfig(gmodule-2.0)
    - pkgconfig(sqlite3)
    - pkgconfig(polkit-gobject-1)
    - pkgconfig(libsystemd)
    - pkgconfig(bash-completion)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(appstream-glib)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(appstream)
    - docbook-xml
    - vala
setup      : |
    %meson_configure -Dpackaging_backend=pisi -Dpythonpackagedir=/usr/lib/python2.7/site-packages/
build      : |
    %ninja_build
install    : |
    %ninja_install
