name        : PackageKit
version     : 1.0.7
release     : 6
source      :
    - http://www.freedesktop.org/software/PackageKit/releases/PackageKit-1.0.7.tar.xz : b186c5b4d53a5dd2ebf8b0c5b255c8a5ef3de6728a6cbeccbf5d1c353cc89c4e
homepage    : http://www.packagekit.org/
license     :
    - GPL-2.0
summary     : D-Bus abstraction layer that allows the session user to manage packages in a secure way using a cross-distro, cross-architecture API.
builddeps   :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(sqlite3)
description : |
    PackageKit is a system designed to make installing and updating software on your computer easier. The primary design goal is to unify all the software graphical tools used in different distributions, and use some of the latest technology like PolicyKit to make the process suck less.
setup      : |
    # TEMPORARY: Swapping for new eopkg soon.
    %configure --enable-pisi \
               --with-default-backend=pisi \
               --disable-dummy \
               --disable-bash-completion \
               --disable-man-pages \
               --disable-static \
               --enable-systemd
build      : |
    %make
install    : |
    %make_install
     
    install -m 00644 -D $pkgfiles/pisi.conf $installdir/etc/PackageKit/pisi.conf
